from __future__ import annotations

import argparse
import glob
import hashlib
import importlib.util
import os
from dataclasses import dataclass
from pathlib import Path
import re
import sys
import tempfile
from types import ModuleType
from typing import Iterable, Sequence


DEFAULT_HEADER = (
    "# @generated by evergen from {source} — SignedHash<<{hash}>> — do not hand-edit"
)
TOKEN_RE = re.compile(r"SignedHash<<([0-9a-fA-F]+)>>")
DIRTY_HELP = (
    "hand-edited; keep your edits by removing the header and deleting the "
    "generator, or discard them with --overwrite"
)
UNMANAGED_HELP = "not generated by evergen; use --overwrite to replace"


class EvergenError(Exception):
    """User-facing error."""


@dataclass(frozen=True)
class Mapping:
    source: Path
    output: Path
    capture: str
    input_pattern: str


@dataclass(frozen=True)
class ExistingState:
    kind: str
    body: str = ""
    stored_hash: str | None = None


@dataclass(frozen=True)
class PlannedFile:
    mapping: Mapping
    body: str
    content: str
    state: ExistingState


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        validate_patterns(args.output, args.inputs, args.header)
        mappings = discover_mappings(args.inputs, args.output, Path.cwd())
        duplicate_errors = find_duplicate_outputs(mappings)
        if duplicate_errors:
            for error in duplicate_errors:
                print(f"ERROR {error}", file=sys.stderr)
            return 1

        planned = plan_files(mappings, args.header)
    except EvergenError as exc:
        print(f"ERROR {exc}", file=sys.stderr)
        return 1

    if args.check:
        return run_check(planned)
    return run_write(planned, overwrite=args.overwrite)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="evergen",
        description="Regenerate output files from trusted Python generator files.",
    )
    parser.add_argument(
        "--output",
        required=True,
        metavar="OUT_PATTERN",
        help="Output pattern containing exactly one {} placeholder.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Write nothing; fail if outputs are missing, dirty, or stale.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Replace unmanaged or hand-edited targets.",
    )
    parser.add_argument(
        "--header",
        default=DEFAULT_HEADER,
        metavar="TEMPLATE",
        help=(
            "Header line template. Must contain {hash} and render a "
            "SignedHash<<...>> token; {source} is optional."
        ),
    )
    parser.add_argument(
        "inputs",
        nargs="+",
        metavar="INPUT_PATTERN",
        help=(
            "Input glob pattern containing exactly one {} placeholder, "
            "or a plain .py generator file."
        ),
    )
    return parser


def validate_patterns(
    output_pattern: str, input_patterns: Iterable[str], header_template: str
) -> None:
    if output_pattern.count("{}") != 1:
        raise EvergenError("--output must contain exactly one {} placeholder")
    for pattern in input_patterns:
        placeholder_count = pattern.count("{}")
        if placeholder_count == 1:
            continue
        if placeholder_count == 0 and not has_glob_magic(pattern):
            continue
        if placeholder_count == 0:
            raise EvergenError(
                f"input pattern {pattern!r} must contain exactly one {{}} placeholder "
                "or be a plain .py file"
            )
        raise EvergenError(
            f"input pattern {pattern!r} must contain exactly one {{}} placeholder"
        )
    if "{hash}" not in header_template:
        raise EvergenError("--header TEMPLATE must contain {hash}")
    if "\n" in header_template or "\r" in header_template:
        raise EvergenError("--header TEMPLATE must be a single line")


def discover_mappings(
    input_patterns: Iterable[str], output_pattern: str, cwd: Path
) -> list[Mapping]:
    mappings: list[Mapping] = []
    for pattern in input_patterns:
        if "{}" not in pattern:
            source_path = Path(pattern)
            if not source_path.is_file():
                raise EvergenError(f"plain input file {pattern!r} does not exist")
            capture = capture_from_plain_file(source_path)
            output_text = output_pattern.replace("{}", capture)
            output_path = resolve_output_path(
                output_text, source_path, cwd, recursive=False
            )
            mappings.append(
                Mapping(
                    source=source_path.resolve(),
                    output=output_path.resolve(strict=False),
                    capture=capture,
                    input_pattern=pattern,
                )
            )
            continue

        recursive = "**" in pattern
        glob_pattern = pattern.replace("{}", "*")
        regex = re.compile(glob_capture_regex(pattern))
        matches = sorted(glob.glob(glob_pattern, recursive=recursive))
        for match in matches:
            match_path = Path(match)
            if not match_path.is_file():
                continue
            normalized_match = match.replace(os.sep, "/")
            capture_match = regex.match(normalized_match)
            if capture_match is None:
                continue
            capture = capture_match.group("capture")
            output_text = output_pattern.replace("{}", capture)
            output_path = resolve_output_path(
                output_text, match_path, cwd, recursive=recursive
            )
            mappings.append(
                Mapping(
                    source=match_path.resolve(),
                    output=output_path.resolve(strict=False),
                    capture=capture,
                    input_pattern=pattern,
                )
            )
    mappings.sort(key=lambda item: os.path.normcase(str(item.source)))
    return mappings


def has_glob_magic(pattern: str) -> bool:
    return any(char in pattern for char in "*?[")


def capture_from_plain_file(path: Path) -> str:
    name = path.name
    if not name.endswith(".py"):
        raise EvergenError(f"plain input file {str(path)!r} must end in .py")
    capture = name[: -len(".py")]
    for suffix in (".eg", ".gen", ".generator"):
        if capture.endswith(suffix):
            return capture[: -len(suffix)]
    return capture


def glob_capture_regex(pattern: str) -> str:
    normalized = pattern.replace(os.sep, "/")
    pieces: list[str] = ["^"]
    i = 0
    while i < len(normalized):
        if normalized.startswith("{}", i):
            pieces.append(r"(?P<capture>[^/]+)")
            i += 2
            continue

        char = normalized[i]
        if char == "*":
            if i + 1 < len(normalized) and normalized[i + 1] == "*":
                i += 2
                if i < len(normalized) and normalized[i] == "/":
                    pieces.append(r"(?:.*/)?")
                    i += 1
                else:
                    pieces.append(r".*")
            else:
                pieces.append(r"[^/]*")
                i += 1
        elif char == "?":
            pieces.append(r"[^/]")
            i += 1
        elif char == "[":
            end = normalized.find("]", i + 1)
            if end == -1:
                pieces.append(re.escape(char))
                i += 1
            else:
                body = normalized[i + 1 : end]
                if body.startswith("!"):
                    body = "^" + re.escape(body[1:])
                else:
                    body = re.escape(body)
                pieces.append("[" + body + "]")
                i = end + 1
        else:
            pieces.append(re.escape(char))
            i += 1
    pieces.append("$")
    return "".join(pieces)


def resolve_output_path(
    output_text: str, source_path: Path, cwd: Path, *, recursive: bool
) -> Path:
    output_path = Path(output_text)
    if output_path.is_absolute():
        return output_path
    if recursive:
        return source_path.parent / output_path
    return cwd / output_path


def find_duplicate_outputs(mappings: Iterable[Mapping]) -> list[str]:
    seen: dict[str, Mapping] = {}
    errors: list[str] = []
    for mapping in mappings:
        key = os.path.normcase(os.path.abspath(mapping.output))
        existing = seen.get(key)
        if existing is None:
            seen[key] = mapping
            continue
        errors.append(
            "duplicate output "
            f"{display_path(mapping.output)} from {display_path(existing.source)} "
            f"and {display_path(mapping.source)}"
        )
    return errors


def plan_files(mappings: Iterable[Mapping], header_template: str) -> list[PlannedFile]:
    planned: list[PlannedFile] = []
    for mapping in mappings:
        body = load_generator(mapping.source)
        digest = content_hash(body)
        source = source_for_header(mapping.source, mapping.output)
        try:
            header = header_template.format(hash=digest, source=source)
        except (KeyError, ValueError) as exc:
            raise EvergenError(f"invalid --header TEMPLATE: {exc}") from exc
        token_match = TOKEN_RE.search(header)
        if token_match is None or token_match.group(1).lower() != digest:
            raise EvergenError(
                "--header TEMPLATE must render the digest inside "
                "SignedHash<<{hash}>> so evergen can recognize the file later"
            )
        content = header + "\n" + body
        state = read_existing_state(mapping.output)
        planned.append(
            PlannedFile(mapping=mapping, body=body, content=content, state=state)
        )
    return planned


def load_generator(path: Path) -> str:
    module_name = "_evergen_" + hashlib.sha256(str(path).encode("utf-8")).hexdigest()
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None:
        raise EvergenError(f"cannot create import spec for {display_path(path)}")
    module = importlib.util.module_from_spec(spec)
    execute_source_without_bytecode_cache(module, path)
    gen = getattr(module, "gen", None)
    if not callable(gen):
        raise EvergenError(f"{display_path(path)} does not expose callable gen()")
    try:
        result = gen()
    except Exception as exc:  # pragma: no cover - exact user-code failure varies.
        raise EvergenError(f"{display_path(path)} gen() failed: {exc}") from exc
    if not isinstance(result, str):
        raise EvergenError(f"{display_path(path)} gen() must return str")
    return result


def execute_source_without_bytecode_cache(module: ModuleType, path: Path) -> None:
    # Read and compile the generator source directly rather than via
    # SourceFileLoader.exec_module: that loader writes __pycache__ beside every
    # generator and can serve a stale .pyc for a same-size edit within one mtime
    # tick, which would silently generate from old source and break determinism.
    source = path.read_text(encoding="utf-8")
    code = compile(source, str(path), "exec")
    exec(code, module.__dict__)


def source_for_header(source: Path, output: Path) -> str:
    return os.path.relpath(source, output.parent).replace(os.sep, "/")


def read_existing_state(path: Path) -> ExistingState:
    if not path.exists():
        return ExistingState("missing")
    try:
        text = path.read_text(encoding="utf-8")
    except IsADirectoryError as exc:
        raise EvergenError(f"{display_path(path)} is a directory") from exc
    signed = find_signed_body(text)
    if signed is None:
        return ExistingState("unmanaged")
    stored_hash, body = signed
    actual_hash = content_hash(body)
    if actual_hash != stored_hash.lower():
        return ExistingState("dirty", body=body, stored_hash=stored_hash)
    return ExistingState("clean", body=body, stored_hash=stored_hash)


def find_signed_body(text: str) -> tuple[str, str] | None:
    lines = text.splitlines(keepends=True)
    for index, line in enumerate(lines[:5]):
        match = TOKEN_RE.search(line)
        if match is not None:
            return match.group(1), "".join(lines[index + 1 :])
    return None


def content_hash(text: str) -> str:
    normalized = normalize_newlines(text)
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()[:16]


def normalize_newlines(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def run_check(planned: Iterable[PlannedFile]) -> int:
    failed = False
    for item in planned:
        status, message = check_status(item)
        print(report_line(status, item.mapping, message))
        if status != "OK":
            failed = True
    return 1 if failed else 0


def check_status(item: PlannedFile) -> tuple[str, str]:
    state = item.state
    if state.kind == "missing":
        return "MISSING", "run evergen"
    if state.kind == "unmanaged":
        return "UNMANAGED", UNMANAGED_HELP
    if state.kind == "dirty":
        return "DIRTY", DIRTY_HELP
    if normalize_newlines(state.body) != normalize_newlines(item.body):
        return "STALE", "rerun evergen"
    return "OK", ""


def run_write(planned: Iterable[PlannedFile], *, overwrite: bool) -> int:
    failed = False
    for item in planned:
        state = item.state
        if state.kind == "unmanaged" and not overwrite:
            print(report_line("REFUSE", item.mapping, UNMANAGED_HELP))
            failed = True
            continue
        if state.kind == "dirty" and not overwrite:
            print(report_line("REFUSE", item.mapping, DIRTY_HELP))
            failed = True
            continue

        atomic_write_text(item.mapping.output, item.content)
        status = "OVERWROTE" if state.kind in {"unmanaged", "dirty"} else "WROTE"
        print(report_line(status, item.mapping, ""))
    return 1 if failed else 0


def atomic_write_text(output: Path, content: str) -> None:
    # Write to a sibling temp file, then os.replace onto the target so a crash
    # mid-write cannot truncate an existing valid output. The temp lives in the
    # target's directory to keep the rename on one filesystem (atomic).
    output.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        dir=output.parent, prefix=output.name + ".", suffix=".tmp"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.replace(tmp_name, output)
    except BaseException:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass
        raise


def report_line(status: str, mapping: Mapping, message: str) -> str:
    line = (
        f"{status} {display_path(mapping.output)} <- {display_path(mapping.source)}"
    )
    if message:
        line += f": {message}"
    return line


def display_path(path: Path) -> str:
    try:
        return os.path.relpath(path, Path.cwd()).replace(os.sep, "/")
    except ValueError:
        return str(path).replace(os.sep, "/")


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
