"""evergen — regenerate output files from trusted Python generator files.

Contract: a generator (e.g. ``name.eg.py``) exposes ``gen() -> str``. evergen
writes ``<header line>\\n<gen() output>`` to the mapped output path. The header
carries a ``SignedHash<<hash>>`` token where hash = sha256 of the body — the
hash domain is everything AFTER the header line, newlines normalized to
``"\\n"`` — truncated to 16 hex chars.

That signature classifies an existing output into one of four states:

    missing    no file at the output path      -> write
    unmanaged  no signed header found          -> refuse unless --overwrite
    dirty      header found, body hash differs -> refuse unless --overwrite
               (someone hand-edited a generated file)
    clean      header found, body hash matches -> rewrite / report OK

Capture pattern: ``--output`` and each input pattern contain exactly one
``{}``. The text the input ``{}`` matched (one path segment; ``**`` elsewhere
in the pattern handles directories) is substituted into the output pattern.

Determinism law: the same generator source produces byte-identical output on
every run, from any working directory.

Trust model: generators are trusted code — evergen imports and executes them.
"""

from __future__ import annotations

import argparse
import glob
import hashlib
import importlib.util
import os
from dataclasses import dataclass
from pathlib import Path
import re
import stat
import sys
import tempfile
from types import ModuleType
from typing import Iterable, Sequence


DEFAULT_HEADER = (
    "# @generated by evergen from {source} — SignedHash<<{hash}>> — do not hand-edit"
)
TOKEN_RE = re.compile(r"SignedHash<<([0-9a-fA-F]+)>>")
# The literal token every custom --header template must carry so a written
# output can be re-identified later. Validated up front (see validate_patterns).
REQUIRED_HEADER_TOKEN = "SignedHash<<{hash}>>"

# Refusal messages name the state and the legal exits: graduate the file
# (remove the header, delete the generator) or discard edits with --overwrite.
DIRTY_HELP = (
    "hand-edited; keep your edits by removing the header and deleting the "
    "generator, or discard them with --overwrite"
)
UNMANAGED_HELP = "not generated by evergen; use --overwrite to replace"


class EvergenError(Exception):
    """User-facing error: caught in main() and printed as ``ERROR <message>``."""


@dataclass(frozen=True)
class Mapping:
    """One generator file resolved to one output path."""

    source: Path
    output: Path
    capture: str  # text the input pattern's {} matched; fills the output {}
    input_pattern: str


@dataclass(frozen=True)
class ExistingState:
    """Classification of the file currently at an output path.

    kind is one of: "missing", "unmanaged", "dirty", "clean" (see module
    docstring). body/stored_hash are populated only when a signed header
    was found (dirty or clean).
    """

    kind: str
    body: str = ""
    stored_hash: str | None = None


# --- header & hash core -----------------------------------------------------


def normalize_newlines(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def content_hash(text: str) -> str:
    # Newlines are normalized before hashing so a CRLF checkout (e.g. git on
    # Windows) still reads as clean. 16 hex chars: the hash is tamper-evidence
    # for accidental edits, not a security boundary.
    normalized = normalize_newlines(text)
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()[:16]


def find_signed_body(text: str) -> tuple[str, str] | None:
    """Return (stored_hash, body_after_header_line) or None if unsigned.

    Scan window is the first 5 lines (headers may sit under a shebang or
    encoding line). The EARLIEST token wins: evergen always writes its header
    on line 1, so a body that itself contains a SignedHash token can never
    shadow the real header.
    """
    lines = text.splitlines(keepends=True)
    for index, line in enumerate(lines[:5]):
        match = TOKEN_RE.search(line)
        if match is not None:
            return match.group(1), "".join(lines[index + 1 :])
    return None


def source_for_header(source: Path, output: Path) -> str:
    # Relative to the OUTPUT's directory, not the cwd, so the header text —
    # and therefore the written bytes — are identical no matter where evergen
    # is invoked from.
    return os.path.relpath(source, output.parent).replace(os.sep, "/")


def read_existing_state(path: Path) -> ExistingState:
    if not path.exists():
        return ExistingState("missing")
    try:
        text = path.read_text(encoding="utf-8")
    except IsADirectoryError as exc:
        raise EvergenError(f"{display_path(path)} is a directory") from exc
    except UnicodeDecodeError:
        # A non-UTF-8 file carries no readable SignedHash token, so it is not
        # something evergen wrote: treat it as unmanaged. --overwrite replaces
        # it; without --overwrite it is refused like any other unmanaged target.
        return ExistingState("unmanaged")
    signed = find_signed_body(text)
    if signed is None:
        return ExistingState("unmanaged")
    stored_hash, body = signed
    actual_hash = content_hash(body)
    if actual_hash != stored_hash.lower():
        return ExistingState("dirty", body=body, stored_hash=stored_hash)
    return ExistingState("clean", body=body, stored_hash=stored_hash)


# --- capture pattern & mapping ----------------------------------------------


def validate_patterns(
    output_pattern: str, input_patterns: Iterable[str], header_template: str
) -> None:
    if output_pattern.count("{}") != 1:
        raise EvergenError("--output must contain exactly one {} placeholder")
    for pattern in input_patterns:
        placeholder_count = pattern.count("{}")
        if placeholder_count == 1:
            continue
        if placeholder_count == 0 and not has_glob_magic(pattern):
            continue
        if placeholder_count == 0:
            raise EvergenError(
                f"input pattern {pattern!r} must contain exactly one {{}} placeholder "
                "or be a plain .py file"
            )
        raise EvergenError(
            f"input pattern {pattern!r} must contain exactly one {{}} placeholder"
        )
    # Validate the header template fully here, before any generator is
    # discovered or executed, so a malformed --header never runs user code.
    # The template must render the digest inside the recognizable token, or
    # read_existing_state could never re-identify our own output; requiring the
    # literal SignedHash<<{hash}>> substring guarantees that after formatting.
    if "\n" in header_template or "\r" in header_template:
        raise EvergenError("--header TEMPLATE must be a single line")
    if REQUIRED_HEADER_TOKEN not in header_template:
        raise EvergenError(
            "--header TEMPLATE must contain the literal token "
            "SignedHash<<{hash}>> so evergen can recognize the file later"
        )


def has_glob_magic(pattern: str) -> bool:
    return any(char in pattern for char in "*?[")


def capture_from_plain_file(path: Path) -> str:
    """Derive the {} capture for a placeholder-free input: the stem of the
    filename, minus a recognized generator suffix (foo.eg.py -> foo)."""
    name = path.name
    if not name.endswith(".py"):
        raise EvergenError(f"plain input file {str(path)!r} must end in .py")
    capture = name[: -len(".py")]
    for suffix in (".eg", ".gen", ".generator"):
        if capture.endswith(suffix):
            return capture[: -len(suffix)]
    return capture


def validate_capture(capture: str, source: Path) -> None:
    # The capture already cannot contain a path separator (see the {} group in
    # glob_capture_regex), but "." and ".." are still single segments that,
    # once substituted into the output pattern and normalized, silently retarget
    # the write at the source's directory or its parent — and a plain input like
    # ".eg.py" strips down to an empty capture, which is no path segment at all.
    # Reject all three outright.
    if capture in {"", ".", ".."}:
        raise EvergenError(
            f"{display_path(source)}: capture {capture!r} is not a valid path segment"
        )


def translate_bracket(pattern: str, start: int) -> tuple[str, int]:
    """Translate the glob bracket expression at ``pattern[start] == '['``.

    Returns ``(regex_fragment, index_just_past_']')``. Ported from CPython's
    ``fnmatch.translate`` so that character classes keep their glob meaning —
    ranges like ``[a-z]`` and negation like ``[!x]`` become real regex classes
    instead of being escaped into a literal set (which silently narrowed
    ``[a-z]`` to the three characters ``a``, ``-``, ``z`` and dropped valid
    matches). A ``[`` with no closing ``]`` is treated as a literal.
    """
    n = len(pattern)
    i = start + 1
    j = i
    if j < n and pattern[j] == "!":
        j += 1
    if j < n and pattern[j] == "]":
        j += 1
    while j < n and pattern[j] != "]":
        j += 1
    if j >= n:
        return "\\[", start + 1
    stuff = pattern[i:j]
    if "-" not in stuff:
        stuff = stuff.replace("\\", r"\\")
    else:
        chunks = []
        k = i + 2 if pattern[i] == "!" else i + 1
        while True:
            k = pattern.find("-", k, j)
            if k < 0:
                break
            chunks.append(pattern[i:k])
            i = k + 1
            k = k + 3
        chunk = pattern[i:j]
        if chunk:
            chunks.append(chunk)
        else:
            chunks[-1] += "-"
        # Remove empty ranges -- invalid in a regex character class.
        for k in range(len(chunks) - 1, 0, -1):
            if chunks[k - 1][-1] > chunks[k][0]:
                chunks[k - 1] = chunks[k - 1][:-1] + chunks[k][1:]
                del chunks[k]
        stuff = "-".join(s.replace("\\", r"\\").replace("-", r"\-") for s in chunks)
    stuff = re.sub(r"([&~|])", r"\\\1", stuff)
    if not stuff:
        return "(?!)", j + 1
    if stuff == "!":
        return ".", j + 1
    if stuff[0] == "!":
        stuff = "^" + stuff[1:]
    elif stuff[0] in ("^", "["):
        stuff = "\\" + stuff
    return "[%s]" % stuff, j + 1


def glob_capture_regex(pattern: str) -> str:
    """Translate an input pattern into a regex over /-normalized paths.

    Mirrors glob semantics so that anything glob.glob matched, this regex can
    re-match to extract the capture. The {} placeholder becomes a named group
    that cannot cross a path separator — directory traversal is only ever
    expressed by an explicit ** in the pattern.
    """
    normalized = pattern.replace(os.sep, "/")
    pieces: list[str] = ["^"]
    i = 0
    n = len(normalized)
    while i < n:
        if normalized.startswith("{}", i):
            pieces.append(r"(?P<capture>[^/]+)")
            i += 2
            continue

        char = normalized[i]
        if char == "*":
            if i + 1 < n and normalized[i + 1] == "*":
                i += 2
                if i < n and normalized[i] == "/":
                    pieces.append(r"(?:.*/)?")
                    i += 1
                else:
                    pieces.append(r".*")
            else:
                pieces.append(r"[^/]*")
                i += 1
        elif char == "?":
            pieces.append(r"[^/]")
            i += 1
        elif char == "[":
            # Delegate the character class to fnmatch-style translation so glob
            # ranges keep their meaning instead of collapsing to literals.
            fragment, i = translate_bracket(normalized, i)
            pieces.append(fragment)
        else:
            pieces.append(re.escape(char))
            i += 1
    pieces.append("$")
    return "".join(pieces)


def resolve_output_path(
    output_text: str, source_path: Path, cwd: Path, *, recursive: bool
) -> Path:
    # Relative outputs anchor at the cwd, except for recursive (**) patterns,
    # which anchor beside each source so a whole tree regenerates in place.
    output_path = Path(output_text)
    if output_path.is_absolute():
        return output_path
    if recursive:
        return source_path.parent / output_path
    return cwd / output_path


def discover_mappings(
    input_patterns: Iterable[str], output_pattern: str, cwd: Path
) -> list[Mapping]:
    mappings: list[Mapping] = []
    for pattern in input_patterns:
        if "{}" not in pattern:
            source_path = Path(pattern)
            if not source_path.is_file():
                raise EvergenError(f"plain input file {pattern!r} does not exist")
            capture = capture_from_plain_file(source_path)
            validate_capture(capture, source_path)
            output_text = output_pattern.replace("{}", capture)
            output_path = resolve_output_path(
                output_text, source_path, cwd, recursive=False
            )
            mappings.append(
                Mapping(
                    source=source_path.resolve(),
                    output=output_path.resolve(strict=False),
                    capture=capture,
                    input_pattern=pattern,
                )
            )
            continue

        recursive = "**" in pattern
        glob_pattern = pattern.replace("{}", "*")
        regex = re.compile(glob_capture_regex(pattern))
        matches = sorted(glob.glob(glob_pattern, recursive=recursive))
        for match in matches:
            match_path = Path(match)
            if not match_path.is_file():
                continue
            normalized_match = match.replace(os.sep, "/")
            capture_match = regex.match(normalized_match)
            if capture_match is None:
                continue
            capture = capture_match.group("capture")
            validate_capture(capture, match_path)
            output_text = output_pattern.replace("{}", capture)
            output_path = resolve_output_path(
                output_text, match_path, cwd, recursive=recursive
            )
            mappings.append(
                Mapping(
                    source=match_path.resolve(),
                    output=output_path.resolve(strict=False),
                    capture=capture,
                    input_pattern=pattern,
                )
            )
    # Deterministic processing (and report) order regardless of glob order.
    mappings.sort(key=lambda item: os.path.normcase(str(item.source)))
    return mappings


def find_duplicate_outputs(mappings: Iterable[Mapping]) -> list[str]:
    seen: dict[str, Mapping] = {}
    errors: list[str] = []
    for mapping in mappings:
        # normcase so two sources cannot silently race for one output on
        # case-insensitive filesystems.
        key = os.path.normcase(os.path.abspath(mapping.output))
        existing = seen.get(key)
        if existing is None:
            seen[key] = mapping
            continue
        errors.append(
            "duplicate output "
            f"{display_path(mapping.output)} from {display_path(existing.source)} "
            f"and {display_path(mapping.source)}"
        )
    return errors


def find_source_output_collisions(mappings: Iterable[Mapping]) -> list[str]:
    # A mapping whose output resolves onto its own generator would have evergen
    # load the generator and then replace it with generated output — e.g.
    # ``--overwrite --output '{}.py' '{}.py'`` destroying the tool itself. Refuse
    # up front, alongside duplicate detection, before anything runs or is written.
    errors: list[str] = []
    for mapping in mappings:
        output_key = os.path.normcase(os.path.abspath(mapping.output))
        source_key = os.path.normcase(os.path.abspath(mapping.source))
        if output_key == source_key:
            errors.append(
                f"output {display_path(mapping.output)} is the same file as its "
                f"generator {display_path(mapping.source)}"
            )
    return errors


# --- generator execution & rendering ----------------------------------------


def load_generator(path: Path) -> str:
    module_name = "_evergen_" + hashlib.sha256(str(path).encode("utf-8")).hexdigest()
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None:
        raise EvergenError(f"cannot create import spec for {display_path(path)}")
    module = importlib.util.module_from_spec(spec)

    # Executing module code must satisfy the normal import invariants:
    #   * the module is registered in sys.modules under its own name, so
    #     ordinary Python (e.g. @dataclass, which looks up
    #     sys.modules[cls.__module__]) works;
    #   * the generator's own directory is on sys.path, so a nested generator
    #     can ``from sibling import ...`` — matching the setup.py trust model.
    # Both are restored in the finally block. A unique per-path module name keeps
    # distinct generators from clobbering one another. Sibling modules the
    # generator imported are evicted from sys.modules afterwards too: without
    # that, two generators in different directories importing a same-named
    # sibling would silently share whichever loaded first, making output depend
    # on co-invocation and violating the determinism law. Stdlib and installed
    # packages keep their normal import caching — only modules whose files live
    # under the generator's own directory are evicted.
    saved_module = sys.modules.get(module_name)
    saved_keys = set(sys.modules)
    saved_path = sys.path[:]
    generator_dir = path.parent.resolve()
    sys.modules[module_name] = module
    sys.path.insert(0, str(path.parent))
    try:
        try:
            execute_source_without_bytecode_cache(module, path)
        except EvergenError:
            raise
        except Exception as exc:  # import-time failure in the generator body.
            raise EvergenError(f"{display_path(path)} failed to import: {exc}") from exc
        gen = getattr(module, "gen", None)
        if not callable(gen):
            raise EvergenError(f"{display_path(path)} does not expose callable gen()")
        try:
            result = gen()
        except Exception as exc:  # pragma: no cover - exact user-code failure varies.
            raise EvergenError(f"{display_path(path)} gen() failed: {exc}") from exc
        if not isinstance(result, str):
            raise EvergenError(f"{display_path(path)} gen() must return str")
        return result
    finally:
        sys.path[:] = saved_path
        if saved_module is not None:
            sys.modules[module_name] = saved_module
        else:
            sys.modules.pop(module_name, None)
        for name in list(sys.modules):
            if name in saved_keys or name == module_name:
                continue
            module_file = getattr(sys.modules[name], "__file__", None)
            if module_file is None:
                continue  # builtins/namespace packages have no file; keep cached.
            if Path(module_file).resolve().is_relative_to(generator_dir):
                del sys.modules[name]


def execute_source_without_bytecode_cache(module: ModuleType, path: Path) -> None:
    # Read and compile the generator source directly rather than via
    # SourceFileLoader.exec_module: that loader writes __pycache__ beside every
    # generator and can serve a stale .pyc for a same-size edit within one mtime
    # tick, which would silently generate from old source and break determinism.
    #
    # Source is passed to compile() as BYTES so Python applies its own source
    # decoding rules — PEP 263 coding cookies and a UTF-8 BOM are honored — while
    # still avoiding the bytecode cache.
    source = path.read_bytes()
    code = compile(source, str(path), "exec")
    exec(code, module.__dict__)


def render_output(mapping: Mapping, header_template: str) -> tuple[str, str]:
    """Execute the generator and render (body, full file content).

    body is the raw gen() return value; content is the header line + newline +
    body. This runs the generator, so callers execute it only when a target's
    state actually requires regenerated bytes.
    """
    body = load_generator(mapping.source)
    digest = content_hash(body)
    source = source_for_header(mapping.source, mapping.output)
    try:
        header = header_template.format(hash=digest, source=source)
    except (KeyError, ValueError, IndexError, AttributeError, TypeError) as exc:
        # str.format field lookups (attribute/index access) can raise more than
        # KeyError/ValueError; rewrap them all so a bad template is a one-line
        # ERROR rather than a traceback.
        raise EvergenError(f"invalid --header TEMPLATE: {exc}") from exc
    content = header + "\n" + body
    return body, content


# --- run modes: --check and write -------------------------------------------

# States that a write refuses without --overwrite: nothing evergen produced.
REFUSE_KINDS = frozenset({"unmanaged", "dirty"})


def refusal_help(kind: str) -> str:
    return UNMANAGED_HELP if kind == "unmanaged" else DIRTY_HELP


def run_check(mappings: Iterable[Mapping], header_template: str) -> int:
    failed = False
    for mapping in mappings:
        # Classify first. MISSING/UNMANAGED/DIRTY are decided from the existing
        # file alone and never need regenerated bytes, so the generator does not
        # run for them. Only a clean (hash-verified) target is regenerated, to
        # tell STALE from OK.
        state = read_existing_state(mapping.output)
        if state.kind == "missing":
            print(report_line("MISSING", mapping, "run evergen"))
            failed = True
            continue
        if state.kind == "unmanaged":
            print(report_line("UNMANAGED", mapping, UNMANAGED_HELP))
            failed = True
            continue
        if state.kind == "dirty":
            print(report_line("DIRTY", mapping, DIRTY_HELP))
            failed = True
            continue

        body, _ = render_output(mapping, header_template)
        if normalize_newlines(state.body) != normalize_newlines(body):
            print(report_line("STALE", mapping, "rerun evergen"))
            failed = True
            continue
        print(report_line("OK", mapping, ""))
    return 1 if failed else 0


def run_write(mappings: Iterable[Mapping], header_template: str, *, overwrite: bool) -> int:
    failed = False
    for mapping in mappings:
        # Classify BEFORE executing the generator: a target evergen would refuse
        # (unmanaged/dirty without --overwrite) is reported without running its
        # generator at all. Other targets still process; every target is
        # reported and any refusal makes the run exit nonzero.
        state = read_existing_state(mapping.output)
        if state.kind in REFUSE_KINDS and not overwrite:
            print(report_line("REFUSE", mapping, refusal_help(state.kind)))
            failed = True
            continue

        _, content = render_output(mapping, header_template)

        # TOCTOU narrowing: re-read and re-classify immediately before the
        # atomic write. If the target changed under us into a state we would
        # have refused, refuse it now instead of clobbering the new edit.
        current = read_existing_state(mapping.output)
        if current.kind in REFUSE_KINDS and not overwrite:
            print(report_line("REFUSE", mapping, refusal_help(current.kind)))
            failed = True
            continue

        try:
            atomic_write_text(mapping.output, content)
        except OSError as exc:
            # Expected filesystem failures (permissions, read-only dir, …) are a
            # one-line ERROR for this target; remaining targets still process.
            print(
                f"ERROR {display_path(mapping.output)} <- "
                f"{display_path(mapping.source)}: {exc}",
                file=sys.stderr,
            )
            failed = True
            continue
        status = "OVERWROTE" if current.kind in REFUSE_KINDS else "WROTE"
        print(report_line(status, mapping, ""))
    return 1 if failed else 0


def current_umask() -> int:
    # There is no read-only query for the umask; set-and-restore is the standard
    # idiom. Used to give new files normal open()-style permissions.
    mask = os.umask(0)
    os.umask(mask)
    return mask


def atomic_write_text(output: Path, content: str) -> None:
    # Write to a sibling temp file, then os.replace onto the target so a crash
    # mid-write cannot truncate an existing valid output. The temp lives in the
    # target's directory to keep the rename on one filesystem (atomic).
    output.parent.mkdir(parents=True, exist_ok=True)

    # Preserve the mode of an existing regular file (e.g. an executable script);
    # for a new file, mimic what a normal open() would create (0666 & ~umask)
    # rather than mkstemp's private 0600.
    prior_mode: int | None = None
    try:
        existing = os.stat(output)
    except FileNotFoundError:
        existing = None
    if existing is not None and stat.S_ISREG(existing.st_mode):
        prior_mode = stat.S_IMODE(existing.st_mode)

    fd, tmp_name = tempfile.mkstemp(
        dir=output.parent, prefix=output.name + ".", suffix=".tmp"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        if prior_mode is not None:
            os.chmod(tmp_name, prior_mode)
        else:
            os.chmod(tmp_name, 0o666 & ~current_umask())
        os.replace(tmp_name, output)
    except BaseException:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass
        raise


# --- reporting ----------------------------------------------------------------


def report_line(status: str, mapping: Mapping, message: str) -> str:
    line = (
        f"{status} {display_path(mapping.output)} <- {display_path(mapping.source)}"
    )
    if message:
        line += f": {message}"
    return line


def display_path(path: Path) -> str:
    # cwd-relative with / separators, purely for readable report lines; falls
    # back to the absolute path when no relative form exists (other drive).
    try:
        return os.path.relpath(path, Path.cwd()).replace(os.sep, "/")
    except ValueError:
        return str(path).replace(os.sep, "/")


# --- CLI ----------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="evergen",
        description="Regenerate output files from trusted Python generator files.",
    )
    parser.add_argument(
        "--output",
        required=True,
        metavar="OUT_PATTERN",
        help="Output pattern containing exactly one {} placeholder.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Write nothing; fail if outputs are missing, dirty, or stale.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Replace unmanaged or hand-edited targets.",
    )
    parser.add_argument(
        "--header",
        default=DEFAULT_HEADER,
        metavar="TEMPLATE",
        help=(
            "Header line template. Must contain {hash} and render a "
            "SignedHash<<...>> token; {source} is optional."
        ),
    )
    parser.add_argument(
        "inputs",
        nargs="+",
        metavar="INPUT_PATTERN",
        help=(
            "Input glob pattern containing exactly one {} placeholder, "
            "or a plain .py generator file."
        ),
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        validate_patterns(args.output, args.inputs, args.header)
        mappings = discover_mappings(args.inputs, args.output, Path.cwd())
        # Preflight refusals — before any generator runs or any file is written.
        preflight_errors = find_duplicate_outputs(mappings)
        preflight_errors += find_source_output_collisions(mappings)
        if preflight_errors:
            for error in preflight_errors:
                print(f"ERROR {error}", file=sys.stderr)
            return 1

        if args.check:
            return run_check(mappings, args.header)
        return run_write(mappings, args.header, overwrite=args.overwrite)
    except EvergenError as exc:
        print(f"ERROR {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
