from __future__ import annotations

from pathlib import Path

import pytest

from evergen.cli import main


def write_gen(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "def gen():\n"
        f"    return {body!r}\n",
        encoding="utf-8",
    )


def run_evergen(capsys: pytest.CaptureFixture[str], *args: str) -> tuple[int, str, str]:
    code = main(list(args))
    captured = capsys.readouterr()
    return code, captured.out, captured.err


def test_capture_pattern_mapping_nonrecursive_and_recursive(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.chdir(tmp_path)
    write_gen(tmp_path / "one.eg.py", 'print("one")\n')
    write_gen(tmp_path / "src" / "pkg" / "two.eg.py", 'print("two")\n')

    code, out, err = run_evergen(capsys, "--output", "out/{}.py", "{}.eg.py")

    assert code == 0, err
    assert "WROTE out/one.py <- one.eg.py" in out
    assert (tmp_path / "out" / "one.py").exists()

    code, out, err = run_evergen(
        capsys, "--output", "{}__out.py", "src/**/{}.eg.py"
    )

    assert code == 0, err
    assert "WROTE src/pkg/two__out.py <- src/pkg/two.eg.py" in out
    assert (tmp_path / "src" / "pkg" / "two__out.py").exists()


def test_default_write_states_missing_clean_unmanaged_and_dirty(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.chdir(tmp_path)
    write_gen(tmp_path / "target.eg.py", 'print("generated")\n')

    code, out, err = run_evergen(capsys, "--output", "{}.py", "{}.eg.py")

    assert code == 0, err
    assert "WROTE target.py <- target.eg.py" in out

    first_bytes = (tmp_path / "target.py").read_bytes()
    code, out, err = run_evergen(capsys, "--output", "{}.py", "{}.eg.py")

    assert code == 0, err
    assert "WROTE target.py <- target.eg.py" in out
    assert (tmp_path / "target.py").read_bytes() == first_bytes

    write_gen(tmp_path / "manual.eg.py", 'print("generated")\n')
    (tmp_path / "manual.py").write_text("print('mine')\n", encoding="utf-8")

    code, out, _ = run_evergen(capsys, "--output", "{}.py", "manual.eg.py")

    assert code == 1
    assert "REFUSE manual.py <- manual.eg.py: not generated by evergen" in out

    (tmp_path / "target.py").write_text(
        (tmp_path / "target.py").read_text(encoding="utf-8") + "# edit\n",
        encoding="utf-8",
    )

    code, out, _ = run_evergen(capsys, "--output", "{}.py", "target.eg.py")

    assert code == 1
    assert "REFUSE target.py <- target.eg.py: hand-edited" in out


def test_check_reports_missing_dirty_stale_and_clean(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.chdir(tmp_path)
    write_gen(tmp_path / "clean.eg.py", 'print("clean")\n')
    write_gen(tmp_path / "dirty.eg.py", 'print("dirty")\n')
    write_gen(tmp_path / "stale.eg.py", 'print("old")\n')
    write_gen(tmp_path / "missing.eg.py", 'print("missing")\n')

    code, _, err = run_evergen(
        capsys, "--output", "{}.py", "clean.eg.py", "dirty.eg.py", "stale.eg.py"
    )
    assert code == 0, err

    (tmp_path / "dirty.py").write_text(
        (tmp_path / "dirty.py").read_text(encoding="utf-8") + "# hand edit\n",
        encoding="utf-8",
    )
    write_gen(tmp_path / "stale.eg.py", 'print("new")\n')

    code, out, _ = run_evergen(
        capsys,
        "--check",
        "--output",
        "{}.py",
        "clean.eg.py",
        "dirty.eg.py",
        "stale.eg.py",
        "missing.eg.py",
    )

    assert code == 1
    assert "OK clean.py <- clean.eg.py" in out
    assert "DIRTY dirty.py <- dirty.eg.py" in out
    assert "STALE stale.py <- stale.eg.py: rerun evergen" in out
    assert "MISSING missing.py <- missing.eg.py: run evergen" in out

    code, out, err = run_evergen(capsys, "--output", "{}.py", "stale.eg.py")
    assert code == 0, err
    code, out, err = run_evergen(capsys, "--check", "--output", "{}.py", "stale.eg.py")
    assert code == 0, err
    assert "OK stale.py <- stale.eg.py" in out


def test_overwrite_replaces_unmanaged_and_dirty(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.chdir(tmp_path)
    write_gen(tmp_path / "manual.eg.py", 'print("generated")\n')
    (tmp_path / "manual.py").write_text("print('mine')\n", encoding="utf-8")

    code, out, _ = run_evergen(capsys, "--output", "{}.py", "manual.eg.py")
    assert code == 1
    assert "not generated by evergen" in out

    code, out, err = run_evergen(
        capsys, "--overwrite", "--output", "{}.py", "manual.eg.py"
    )
    assert code == 0, err
    assert "OVERWROTE manual.py <- manual.eg.py" in out

    write_gen(tmp_path / "dirty.eg.py", 'print("fresh")\n')
    code, _, err = run_evergen(capsys, "--output", "{}.py", "dirty.eg.py")
    assert code == 0, err
    (tmp_path / "dirty.py").write_text(
        (tmp_path / "dirty.py").read_text(encoding="utf-8") + "# edit\n",
        encoding="utf-8",
    )

    code, out, _ = run_evergen(capsys, "--output", "{}.py", "dirty.eg.py")
    assert code == 1
    assert "hand-edited" in out

    code, out, err = run_evergen(
        capsys, "--overwrite", "--output", "{}.py", "dirty.eg.py"
    )
    assert code == 0, err
    assert "OVERWROTE dirty.py <- dirty.eg.py" in out


def test_duplicate_outputs_fail_before_any_write(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.chdir(tmp_path)
    write_gen(tmp_path / "a" / "same.eg.py", 'print("a")\n')
    write_gen(tmp_path / "b" / "same.eg.py", 'print("b")\n')

    code, out, err = run_evergen(
        capsys, "--output", "{}.py", "a/{}.eg.py", "b/{}.eg.py"
    )

    assert code == 1
    assert out == ""
    assert "ERROR duplicate output same.py" in err
    assert not (tmp_path / "same.py").exists()


def test_header_decoration_still_detects_generated_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.chdir(tmp_path)
    write_gen(tmp_path / "asset.eg.py", "console.log('ok')\n")
    header = "// generated asset SignedHash<<{hash}>> from {source}"

    code, _, err = run_evergen(
        capsys, "--header", header, "--output", "{}.js", "{}.eg.py"
    )
    assert code == 0, err
    assert (tmp_path / "asset.js").read_text(encoding="utf-8").startswith(
        "// generated asset SignedHash<<"
    )

    code, out, err = run_evergen(
        capsys, "--check", "--header", header, "--output", "{}.js", "{}.eg.py"
    )
    assert code == 0, err
    assert "OK asset.js <- asset.eg.py" in out


def test_crlf_checked_out_output_is_not_dirty_or_stale(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.chdir(tmp_path)
    write_gen(tmp_path / "line.eg.py", 'print("a")\nprint("b")\n')

    code, _, err = run_evergen(capsys, "--output", "{}.py", "{}.eg.py")
    assert code == 0, err
    output = tmp_path / "line.py"
    output.write_bytes(output.read_bytes().replace(b"\n", b"\r\n"))

    code, out, err = run_evergen(capsys, "--check", "--output", "{}.py", "{}.eg.py")

    assert code == 0, err
    assert "OK line.py <- line.eg.py" in out


def test_two_runs_are_byte_identical(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.chdir(tmp_path)
    write_gen(tmp_path / "stable.eg.py", 'VALUE = 1\n')

    code, _, err = run_evergen(capsys, "--output", "{}.py", "{}.eg.py")
    assert code == 0, err
    first = (tmp_path / "stable.py").read_bytes()

    code, _, err = run_evergen(capsys, "--output", "{}.py", "{}.eg.py")
    assert code == 0, err

    assert (tmp_path / "stable.py").read_bytes() == first


def test_dotted_generator_filename_is_loadable(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.chdir(tmp_path)
    write_gen(tmp_path / "summary.eg.py", 'print("summary")\n')

    code, out, err = run_evergen(capsys, "--output", "{}.out.py", "{}.eg.py")

    assert code == 0, err
    assert "WROTE summary.out.py <- summary.eg.py" in out
    assert 'print("summary")' in (tmp_path / "summary.out.py").read_text(
        encoding="utf-8"
    )

